# Use official Node image
FROM node:20-alpine

# Set working directory
WORKDIR /

# Copy package files first (better caching)
COPY package.json ./

# Install dependencies
RUN npm install

# Copy app source
COPY App .

# Expose app port
EXPOSE 3000

# Start the app
CMD ["node", "App/AppointMentService/AppointmentService.js"]